export type OrganizationResponse = {
  regNum: number;
  orgType: string;
  orgName: string;
  orgEmail: string;
  orgAddress: string;
  applicationUserId: string;
  applicationUser: {
    firstName: string;
    lastName: string;
    middleName: string;
    refreshToken: string;
    refreshTokenExpiryTime: string;
    id: string;
    userName: string;
    normalizedUserName: string;
    email: string;
    normalizedEmail: string;
    emailConfirmed: boolean;
    passwordHash: string;
    securityStamp: string;
    concurrencyStamp: string;
    phoneNumber: any;
    phoneNumberConfirmed: boolean;
    twoFactorEnabled: boolean;
    lockoutEnd: any;
    lockoutEnabled: boolean;
    accessFailedCount: number;
  };
};
